training:
  epochs: 5
  batch_size: 16
  learning_rate: 0.001
  learning_rate_min: 1e-6
  weight_decay: 0.0001

datasets:
  - name: "drill_hd"
    type: "bop" 
    weight: 0.45
  
  - name: "dataset/drill_cut"
    type: "bop"
    weight: 0.35

  - name: "drill_synt"
    type: "pseudo_label"
    weight: 0.2

